# Generated by Django 4.2.7 on 2026-04-22 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('volume_ml', models.IntegerField(default=450)),
                ('blood_group', models.CharField(max_length=3)),
                ('hiv_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=4)),
                ('hep_b_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=4)),
                ('hep_c_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=4)),
                ('malaria_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=4)),
                ('syphilis_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=4)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
