# Generated by Django 4.2.7 on 2026-04-22 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '__first__'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('collected_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='available', max_length=10)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('donation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.donation')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_requests.bloodrequest')),
            ],
        ),
    ]
